# Generated by Django 5.2 on 2025-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('finances', 'Finances'), ('others', 'Others')], default='personal', error_messages={'invalid_choice': 'Type must be one of: personal, work, finances, others'}, max_length=10),
        ),
    ]
